### ISSUE TITLE
Проблемы поиска

### ISSUE THREAD

**Issue by avasyukov** [tungstencucumber/struct_to_class#4]
Берём такой тестовый main:
```
int main()
{
    Container* c = new Fleet();

    for(int i = 1; i < 10; i++)
        c->insert(i*i);

    cout << boolalpha;
    cout << "Value 25 found: " << c->exists(25) << endl;
    cout << "Value 111 found: " << c->exists(111) << endl;

    delete c;
    return 0;
}
```
Видим на экране:
```
Value 25 found: false
Value 111 found: false
```
Хотя значение 25 мы явно в контейнер складывали.

**Comment by tungstencucumber** [comment]
Закрыто последним коммитом.

**Comment by avasyukov** [comment]
Таки не закрыто. По-прежнему:
```
Value 25 found: false
Value 111 found: false
```

Проблема вот здесь:
https://github.com/tungstencucumber/struct_to_class/blob/0c7cd0b3190a692141fcc3f3409163b1848b9866/main.cpp#L110-L118
Поиск как будто стал рекурсивным, но на самом деле нет - рекурсивно найденное значение игнорируется, а не возвращается вызвавшему.
